### PR TITLE
Feature/dockerise

### PR DESCRIPTION
**Pull request by halissonvit**
Add docker files and instructions to use it.

### CODE REVIEW

**Comment by halissonvit** [comment]
I wanted to give it a try and decided to dockerise the app to make it easier to run. Some changes were necessary to make it work with docker (also to implement some best practices).
Please let me know if that's useful for you guys, or if it need any changes.

Btw, Thanks for the awesome project 😄

**Comment by stpnlr** [comment]
@halissonvit That was cool. We were beginning to dockerize fluxday. Will review the code and merge soon.

**Comment by jannisch** [comment]
I'd love to see this, are there any updates?

**Comment by ismudnx** [comment]
Merged. Instructions needs some update.

**Pull request merged**
